version: '3.8'

services:
  app:
    build: ./ 
    networks:
      - internal
    depends_on:
      - postgres
      - jaeger
    ports:
      - "8000:8080" 

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - internal

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp # accept zipkin.thrift over compact thrift protocol
      - 6831:6831/udp # accept jaeger.thrift over compact thrift protocol
      - 6832:6832/udp # accept jaeger.thrift over binary thrift protocol
      - 5778:5778 # serve configs
      - 16686:16686 # serve frontend
      - 14268:14268 # accept jaeger.thrift directly from clients
      - 4317:4317
      - 4318:4318 
    networks:
      - internal

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - internal    

networks:
  internal:
    driver: bridge
